from flask import Blueprint
from flask_restx import Api
from app.docs import BookDoc

authorizations = {
  'bearerAuth': {
    'type': 'apiKey',
    'name': 'Authorization',
    'in': 'header',
    'description': 'For accessing the API a valid JWT token must be passed in all the queries in the \'Authorization\' header. A valid JWT token is generated by the API and retured as answer of a call to the route /login giving a valid user & password.'
  }
}
document = Blueprint('api_doc', __name__)
api_extension = Api(
  document,
  title='Bookstore Microservice',
  version='1.0',
  description='Bookstore Microservice API Documentation',
  doc='/docs',
  authorizations=authorizations,
  security='bearerAuth'
)

api_extension.add_namespace(BookDoc.api, path='/master/books')