"""empty message

Revision ID: 6ac10962b359
Revises: ce5537ea0209
Create Date: 2024-01-03 12:56:36.905552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ac10962b359'
down_revision = 'ce5537ea0209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice', sa.String(length=25), nullable=False))
        batch_op.drop_column('invoince')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoince', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False))
        batch_op.drop_column('invoice')

    # ### end Alembic commands ###
